PREFIX ?= /usr/local
BINARY = apfel
VERSION_FILE = .version

.PHONY: check-toolchain build install uninstall clean bump-patch bump-minor bump-major generate-build-info update-readme version release-minor release-major

# --- Environment checks ---

check-toolchain:
	@sdk=$$(xcrun --show-sdk-version 2>/dev/null || echo "missing"); \
	devdir=$$(xcode-select -p 2>/dev/null || echo "missing"); \
	os_ver=$$(sw_vers -productVersion 2>/dev/null || echo "unknown"); \
	if [ "$$sdk" = "missing" ]; then \
		echo ""; \
		echo "error: apfel could not determine your active Apple SDK version."; \
		echo "Selected developer dir: $$devdir"; \
		echo "Install or update Command Line Tools (or Xcode), then retry."; \
		echo ""; \
		echo "Checks:"; \
		echo "  xcode-select -p"; \
		echo "  xcrun --show-sdk-version"; \
		exit 1; \
	fi; \
	major=$$(echo "$$sdk" | cut -d. -f1); \
	minor=$$(echo "$$sdk" | cut -d. -f2); \
	if [ -z "$$minor" ]; then minor=0; fi; \
	if [ "$$major" -lt 26 ] || { [ "$$major" -eq 26 ] && [ "$$minor" -lt 4 ]; }; then \
		echo ""; \
		echo "error: apfel requires Apple developer tools with the macOS 26.4 SDK or newer."; \
		echo "Your macOS version: $$os_ver"; \
		echo "Active SDK version: $$sdk"; \
		echo "Selected developer dir: $$devdir"; \
		echo ""; \
		echo "Why this fails:"; \
		echo "  FoundationModels token-counting APIs (tokenCount/contextSize) are missing from older SDKs."; \
		echo ""; \
		echo "What you need to update:"; \
		echo "  1. Update Command Line Tools or install Xcode 26.4+."; \
		echo "  2. If Xcode 26.4+ is already installed, select it:"; \
		echo "     sudo xcode-select -s /Applications/Xcode.app/Contents/Developer"; \
		echo "  3. Re-check with: xcrun --show-sdk-version"; \
		echo "  4. Re-run: make install"; \
		exit 1; \
	fi

# --- Build (auto-bumps patch) ---

build: check-toolchain bump-patch generate-build-info update-readme
	swift build -c release

install: build
	@pkill -f "apfel --serve" 2>/dev/null || true
	@pkill -f "apfel --gui" 2>/dev/null || true
	@sleep 1
	@if [ -w "$(PREFIX)/bin" ]; then \
		install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	else \
		sudo install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	fi
	@echo "✓ installed: $$($(PREFIX)/bin/$(BINARY) --version)"

# --- Version bumps ---

bump-patch:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	patch=$$(echo $$v | cut -d. -f3); \
	new="$$major.$$minor.$$((patch+1))"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v → $$new"

bump-minor:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	new="$$major.$$((minor+1)).0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v → $$new"

bump-major:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	new="$$((major+1)).0.0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v → $$new"

# --- Release targets (bump without extra patch increment) ---

release-minor: check-toolchain bump-minor generate-build-info update-readme
	swift build -c release

release-major: check-toolchain bump-major generate-build-info update-readme
	swift build -c release

# --- Generated files ---

generate-build-info:
	@v=$$(cat $(VERSION_FILE)); \
	commit=$$(git rev-parse --short HEAD 2>/dev/null || echo "unknown"); \
	branch=$$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown"); \
	date=$$(date -u +"%Y-%m-%d %H:%M:%S UTC"); \
	swift_ver=$$(swift --version 2>/dev/null | head -1 | sed 's/.*version //' | sed 's/ .*//'); \
	os_ver=$$(sw_vers -productVersion 2>/dev/null || echo "unknown"); \
	echo "// Auto-generated by make — do not edit" > Sources/BuildInfo.swift; \
	echo "let buildVersion = \"$$v\"" >> Sources/BuildInfo.swift; \
	echo "let buildCommit = \"$$commit\"" >> Sources/BuildInfo.swift; \
	echo "let buildBranch = \"$$branch\"" >> Sources/BuildInfo.swift; \
	echo "let buildDate = \"$$date\"" >> Sources/BuildInfo.swift; \
	echo "let buildSwiftVersion = \"$$swift_ver\"" >> Sources/BuildInfo.swift; \
	echo "let buildOS = \"macOS $$os_ver\"" >> Sources/BuildInfo.swift

update-readme:
	@v=$$(cat $(VERSION_FILE)); \
	sed -i '' 's/Version [0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/Version '"$$v"'/' README.md; \
	sed -i '' 's/version-[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*-blue/version-'"$$v"'-blue/' README.md

# --- Utilities ---

version:
	@cat $(VERSION_FILE)

uninstall:
	@if [ -w "$(PREFIX)/bin" ]; then \
		rm -f $(PREFIX)/bin/$(BINARY); \
	else \
		sudo rm -f $(PREFIX)/bin/$(BINARY); \
	fi

clean:
	swift package clean
