// Auto-generated by make — do not edit
let buildVersion = "0.9.15"
let buildCommit = "e139c31"
let buildBranch = "feat/cli-parse-validate-split"
let buildDate = "2026-04-11 13:29:00 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
