// Auto-generated by make — do not edit
let buildVersion = "1.3.3"
let buildCommit = "f72cb5b"
let buildBranch = "main"
let buildDate = "2026-04-27 09:44:26 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
