// Auto-generated by make — do not edit
let buildVersion = "0.6.35"
let buildCommit = "75becc0"
let buildBranch = "main"
let buildDate = "2026-04-04 07:45:04 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
